### ISSUE TITLE
云原神的token如何获取

### ISSUE THREAD

**Issue by dong-dong6** [Womsxd/MihoyoBBSTools#10]
<img width="592" alt="image" src="https://user-images.githubusercontent.com/73739354/222075043-02a0a671-1243-4c51-86a3-2fda06f12e45.png">
云原神的token如何获取

**Comment by 3054528216** [comment]
云原神的token需要哪些参数

**Comment by dong-dong6** [comment]
我并不清楚
________________________________

**Comment by jqtmviyu** [comment]
> 云原神的token需要哪些参数

ai=xxx;ci=xxx;oi=xxx;ct=xxx;si=xxx;bi=xxx
