### ISSUE TITLE
最近打码一直报错，麻烦看一下吧

### ISSUE THREAD

**Issue by w211691** [Womsxd/MihoyoBBSTools#100]
![QQ截图20231126111311](https://github.com/Womsxd/MihoyoBBSTools/assets/47178067/3abef3f6-f538-43b4-bb6a-7155760a8bde)
用的还是人人打码，最新的API也改过了，但是打码平台那边每次都是提示错误，不知道为什么。。。

**Comment by Womsxd** [comment]
打码不管，要请自己在报错的rep前面加print(rep)后续自己解决
