### ISSUE TITLE
本地用Python运行报错 有没有大佬帮看下是什么问题

### ISSUE THREAD

**Issue by gdf159159** [Womsxd/MihoyoBBSTools#116]
![微信截图_20240123100100](https://github.com/Womsxd/MihoyoBBSTools/assets/8487256/fc56bd24-2549-4085-9200-dd2009d01e7e)

**Comment by Womsxd** [comment]
是不是用记事本改，编码问题，用npp/vscode

**Comment by gdf159159** [comment]
> 是不是用记事本改，编码问题，用npp/vscode

我改了 config.yaml  编码是utf-8  用phpstorm改的

然后想输出日志   logging.ini.example 重命名成  logging.ini  就提示截图的错误

删掉logging.ini 就正常运行

**Comment by gdf159159** [comment]
> 是不是用记事本改，编码问题，用npp/vscode

我找到了问题  需要在loghelper.py第9行添加,encoding='utf-8'
