### ISSUE TITLE
[Question]black_list字段该如何填写

### ISSUE THREAD

**Issue by gongfuture** [Womsxd/MihoyoBBSTools#118]
如题，尝试了几次，也试图阅读代码，还是没有搞懂这个该怎么填写

**Comment by Womsxd** [comment]
if account[1] in config.config["games"]["cn"][self.game_mid]["black_list"]:
                continue

**Comment by Womsxd** [comment]
我没记错的话应该是["111","222"]

**Comment by Womsxd** [comment]
yaml格式化之后可能变成

**Comment by gongfuture** [comment]
那  填什么呢，uid吗？

**Comment by gongfuture** [comment]
啊可以了可以了，之前没触发格式化所以没行，这下可以了

**Comment by Womsxd** [comment]
主要这个功能我也没怎么用(

**Comment by gongfuture** [comment]
> 主要这个功能我也没怎么用(

（）
我是崩三有一个不用的安卓区的号，每次签到还要浪费一次打码，寻思着给拉黑名单里节省一下（
