### ISSUE TITLE
青龙报错

### ISSUE THREAD

**Issue by fplj-fplj** [Womsxd/MihoyoBBSTools#123]

**Comment by fplj-fplj** [comment]
![image](https://github.com/Womsxd/MihoyoBBSTools/assets/103011028/3edd8314-b613-4430-89ab-b66891932b64)

**Comment by Womsxd** [comment]
感觉是文件没拉完整

**Comment by fplj-fplj** [comment]
现在又出现这个
![image](https://github.com/Womsxd/MihoyoBBSTools/assets/103011028/3c5579ed-7c07-4d0a-ae65-b440199e9177)
按照你的教程或者是别人的都不行，但重拉一遍库就好了

**Comment by fplj-fplj** [comment]
就逆天

**Comment by Womsxd** [comment]
e这个是我昨天刚写出的bug（
