### ISSUE TITLE
米忽悠之前更新了原神赛事网站，有两个活跃任务是每天刷新的，大佬是否有意向加到自动化脚本中？

### ISSUE THREAD

**Issue by Yoimiya-993** [Womsxd/MihoyoBBSTools#125]
[https://www.miyoushe.com/ys/article/48541775](https://www.miyoushe.com/ys/article/48541775)
![image](https://github.com/Womsxd/MihoyoBBSTools/assets/52495231/fb4f5fc7-dc64-443b-bafb-d4d86284920c)
[https://webstatic.mihoyo.com/ys/event/tcgmatch/#/bonus/tasks](https://webstatic.mihoyo.com/ys/event/tcgmatch/#/bonus/tasks)
![image](https://github.com/Womsxd/MihoyoBBSTools/assets/52495231/d4d5ff80-45ad-4cdf-842a-fad66351ff97)

**Comment by Womsxd** [comment]
可，最近准备更新config，可以尝试进行加入

**Comment by Womsxd** [comment]
但可能不会最近立刻更新，而是会延后一段时间

**Comment by Yoimiya-993** [comment]
> 但可能不会最近立刻更新，而是会延后一段时间 也就是config先添加，然后后续再来补上这个功能

谢谢大佬！没事，不着急
那个每周任务应该也能写到自动脚本里，加个判断条件让它在周日执行

**Comment by Womsxd** [comment]
每日这个是被注释掉的目前，后续的改动的话要等一下了，现在默认签第一个账号，对只绑定一个号的无影响

**Comment by Womsxd** [comment]
改了，你先别暂停视频吧

**Comment by Womsxd** [comment]
改了，你先暂停自动视频吧 @Yoimiya-993

**Comment by Yoimiya-993** [comment]
好的

**Comment by Womsxd** [comment]
> 好的

这块估计还要改，我等下只保留每日签到，剩下的我先写进去代码里面，

**Comment by Yoimiya-993** [comment]
OK
