### ISSUE TITLE
关于本地能正常运行上传到腾讯云函数后报错

### ISSUE THREAD

**Issue by FKRiX** [Womsxd/MihoyoBBSTools#129]
大佬你好，我这边按照教程在本地部署先，到第二步pip3 install -r requirements_qcloud.txt -t .，由于没有requirements_qcloud.txt所以我使用pip3 install -r requirements.txt -t .这条命令了（可能就是因为这个问题？），虽然执行时也有报红，但是后续测试时正常
![QQ截图20240305235105](https://github.com/Womsxd/MihoyoBBSTools/assets/59141661/062acd19-1904-403a-83d9-e0830f57a422)

而后将文件夹上传python3.6的腾讯云后则报这些错：
START RequestId: 2a8bdf20-f510-48b0-9c72-dcf5dc71cc0a

Init Report RequestId: 2a8bdf20-f510-48b0-9c72-dcf5dc71cc0a Coldstart: 250ms (PullCode: 0ms InitRuntime: 4ms InitFunction: 246ms) Memory: 128MB MemUsage: 10.74MB

ERROR RequestId: 2a8bdf20-f510-48b0-9c72-dcf5dc71cc0a Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/index.py", line 1, in <module>     import main   File "/var/user/main.py", line 5, in <module>     import push   File "/var/user/push.py", line 8, in <module>     from request import http, get_new_session_use_proxy   File "/var/user/request.py", line 48, in <module>     http = get_new_session()   File "/var/user/request.py", line 7, in get_new_session     import httpx   File "/var/user/httpx/__init__.py", line 2, in <module>     from ._api import delete, get, head, options, patch, post, put, request, stream   File "/var/user/httpx/_api.py", line 1     from __future__ import annotations                                      ^ SyntaxError: future feature annotations is not defined", "statusCode": 443}

END RequestId: 2a8bdf20-f510-48b0-9c72-dcf5dc71cc0a

Report RequestId: 2a8bdf20-f510-48b0-9c72-dcf5dc71cc0a Duration: 0ms Memory: 128MB MemUsage: 10.74MB

START RequestId:2a8bdf20-f510-48b0-9c72-dcf5dc71cc0a

ERROR RequestId:2a8bdf20-f510-48b0-9c72-dcf5dc71cc0a Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 1, in \u003cmodule\u003e\n    import main\n  File \"/var/user/main.py\", line 5, in \u003cmodule\u003e\n    import push\n  File \"/var/user/push.py\", line 8, in \u003cmodule\u003e\n    from request import http, get_new_session_use_proxy\n  File \"/var/user/request.py\", line 48, in \u003cmodule\u003e\n    http = get_new_session()\n  File \"/var/user/request.py\", line 7, in get_new_session\n    import httpx\n  File \"/var/user/httpx/__init__.py\", line 2, in \u003cmodule\u003e\n    from ._api import delete, get, head, options, patch, post, put, request, stream\n  File \"/var/user/httpx/_api.py\", line 1\n    from __future__ import annotations\n                                     ^\nSyntaxError: future feature annotations is not defined","statusCode":443}

END RequestId:2a8bdf20-f510-48b0-9c72-dcf5dc71cc0a

Report RequestId:2a8bdf20-f510-48b0-9c72-dcf5dc71cc0a Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by Womsxd** [comment]
可以上腾讯云的python3.8或以上的环境吗？

**Comment by Womsxd** [comment]
请选择python3.9作为运行环境，readme过时了，已更新

**Comment by FKRiX** [comment]
解决了，感谢大佬的回复

腾讯云3.9因为缺少requests会报错，直接pip install会触发类似这个的错误https://github.com/Womsxd/MihoyoBBSTools/issues/41

根据教程在本地文件夹再执行`pip3 install requests~=2.26.0 -t .`，再上传到python3.9的腾讯云后可以正常运行

**Comment by Womsxd** [comment]
> 解决了，感谢大佬的回复
> 
> 腾讯云3.9因为缺少requests会报错，直接pip install会触发类似这个的错误#41
> 
> 根据教程在本地文件夹再执行`pip3 install requests~=2.26.0 -t .`，再上传到python3.9的腾讯云后可以正常运行

httpx无法在腾讯云上面运行吗？或者更新的python3.10

**Comment by FKRiX** [comment]
已经解决了，3.9的python跟上readme走一遍再安装2.26.0的requests就万事大吉了

**Comment by cooper1x** [comment]
```
START RequestId:ae4eaac0-6cf1-44bf-aeb7-9f6c1a11dc7d

ERROR RequestId:ae4eaac0-6cf1-44bf-aeb7-9f6c1a11dc7d Result:{"errorCode":-1,"errorMessage":"ServiceSuspended","statusCode":402}

END RequestId:ae4eaac0-6cf1-44bf-aeb7-9f6c1a11dc7d

Report RequestId:ae4eaac0-6cf1-44bf-aeb7-9f6c1a11dc7d Duration:0ms Memory:128MB MemUsage:0.000000MB
```
我的云函数返回结果是这样的，怎么回事呢。 @Womsxd
