### ISSUE TITLE
cookie中没有'login_ticket'字段

### ISSUE THREAD

**Issue by ShiDai567** [Womsxd/MihoyoBBSTools#130]
2024-03-14T12:01:33 ERROR cookie中没有'login_ticket'字段,请重新登录米游社，重新抓取cookie!

**Comment by ShiDai567** [comment]
我把cookie全部复制到配置文件上了，显示上述报错，大佬能解释一下吗？

**Comment by Womsxd** [comment]
user登了吗？

**Comment by ShiDai567** [comment]
> user登了吗？

就是登录账号后复制的cookie，然后把他粘到cookie的值里，我用的青龙面板运行的，就会抱这个错

**Comment by Womsxd** [comment]
> > user登了吗？
> 
> 就是登录账号后复制的cookie，然后把他粘到cookie的值里，我用的青龙面板运行的，就会抱这个错

https://user.mihoyo.com/#/account/home 登这里，然后拿cookie填
