### ISSUE TITLE
我的cofig目录下只有一个config.yaml文件，但是运行的时候会提示搜索到两个配置文件，另一个是 ._config.yaml文件。导致运行失败

### ISSUE THREAD

**Issue by CookieJaySJ** [Womsxd/MihoyoBBSTools#131]
mihoyo  | 2024-03-14T23:22:43 INFO 使用DOCKER运行米游社签到
mihoyo  | 2024-03-14T23:22:43 INFO Starting signing
mihoyo  | 2024-03-14T23:22:44 INFO AutoMihoyoBBS Multi User mode
mihoyo  | 2024-03-14T23:22:44 INFO 正在搜索配置文件！
mihoyo  | 2024-03-14T23:22:44 INFO 已搜索到2个配置文件，正在开始执行！
mihoyo  | 2024-03-14T23:22:44 INFO 正在执行config.yaml
mihoyo  | 2024-03-14T23:22:44 INFO Config加载完毕
mihoyo  | 2024-03-14T23:22:44 INFO 正在获取任务列表
mihoyo  | 2024-03-14T23:22:45 INFO 今天已经全部完成了！一共获得90个米游币，目前有770个米游币
mihoyo  | 2024-03-14T23:22:51 INFO 正在进行崩坏: 星穹铁道签到
mihoyo  | 2024-03-14T23:22:51 INFO 正在获取米哈游账号绑定的崩坏： 星穹铁道账号列表...
mihoyo  | 2024-03-14T23:22:51 INFO 已获取到1个崩坏： 星穹铁道账号信息
mihoyo  | 2024-03-14T23:22:51 INFO 正在获取签到奖励列表...
mihoyo  | 2024-03-14T23:22:51 INFO 正在为开拓者xxx进行签到...
mihoyo  | 2024-03-14T23:22:57 INFO 开拓者xxx今天已经签到过了~
mihoyo  | 今天获得的奖励是信用点x5000
mihoyo  | 2024-03-14T23:22:57 INFO config.yaml执行完毕
mihoyo  | 2024-03-14T23:23:04 INFO 正在执行._config.yaml
mihoyo  | Traceback (most recent call last):
mihoyo  |   File "/var/app/./main_multi.py", line 91, in <module>
mihoyo  |     main_multi(autorun)
mihoyo  |   File "/var/app/./main_multi.py", line 57, in main_multi
mihoyo  |     run_code, run_message = main.main()
mihoyo  |                             ^^^^^^^^^^^
mihoyo  |   File "/var/app/main.py", line 25, in main
mihoyo  |     config.load_config()
mihoyo  |   File "/var/app/config.py", line 139, in load_config
mihoyo  |     data = yaml.load(f, Loader=yaml.FullLoader)
mihoyo  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mihoyo  |   File "/usr/local/lib/python3.12/site-packages/yaml/__init__.py", line 79, in load
mihoyo  |     loader = Loader(stream)
mihoyo  |              ^^^^^^^^^^^^^^
mihoyo  |   File "/usr/local/lib/python3.12/site-packages/yaml/loader.py", line 24, in __init__
mihoyo  |     Reader.__init__(self, stream)
mihoyo  |   File "/usr/local/lib/python3.12/site-packages/yaml/reader.py", line 85, in __init__
mihoyo  |     self.determine_encoding()
mihoyo  |   File "/usr/local/lib/python3.12/site-packages/yaml/reader.py", line 124, in determine_encoding
mihoyo  |     self.update_raw()
mihoyo  |   File "/usr/local/lib/python3.12/site-packages/yaml/reader.py", line 178, in update_raw
mihoyo  |     data = self.stream.read(size)
mihoyo  |            ^^^^^^^^^^^^^^^^^^^^^^
mihoyo  |   File "<frozen codecs>", line 322, in decode
mihoyo  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
mihoyo  | 2024-03-14T23:23:04 INFO Current running datetime: 2024-03-14 23:23:04
mihoyo  | 2024-03-14T23:23:04 INFO Next run datetime: 2024-03-15 09:30:17

**Comment by Womsxd** [comment]
Linux吗？Linux下.开头是隐藏文件，你可以cat看看没啥用就删除，或者使用指定文件前缀功能

**Comment by CookieJaySJ** [comment]
> Linux吗？Linux下.开头是隐藏文件，你可以cat看看没啥用就删除，或者使用指定文件前缀功能

是群晖，之前版本没有这个bug。  大佬我想问一下怎么指定文件前缀？

**Comment by Womsxd** [comment]
环境变量加入：AutoMihoyoBBS_config_prefix ，可以看青龙环境变量这一部分的内容

**Comment by CookieJaySJ** [comment]
> 环境变量加入：AutoMihoyoBBS_config_prefix ，可以看青龙环境变量这一部分的内容

谢谢🙏

**Comment by Womsxd** [comment]
单用户的话也可以修改docker-compose.yml文件，把docker的环境变量MULTI改为FALSE

**Comment by CookieJaySJ** [comment]
> 单用户的话也可以修改docker-compose.yml文件，把docker的环境变量MULTI改为FALSE



> FALSE

这样设置就可以了 谢谢大佬
