### ISSUE TITLE
打码成功之后依然报错

### ISSUE THREAD

**Issue by Shuai-Bi** [Womsxd/MihoyoBBSTools#138]
![{122B299D-5E63-4b8c-90D9-C0DB80EEAB56}](https://github.com/Womsxd/MihoyoBBSTools/assets/56588474/de08a841-721f-4bf9-aa68-b492c6880745)
![{382D9A22-E117-4a18-94D0-6AD762911297}](https://github.com/Womsxd/MihoyoBBSTools/assets/56588474/8f2fa525-ba57-4a25-88e3-4cfa9da55c8d)
删除条件中的data.get("data").get("success",-1)之后：

![{A4E10FB2-8FE7-4839-9142-1A4F1D131A88}](https://github.com/Womsxd/MihoyoBBSTools/assets/56588474/2d5ba1ea-135f-424e-9ab6-7c492e90360d)

**Comment by Womsxd** [comment]
尝试重新执行？

**Comment by Shuai-Bi** [comment]
> 尝试重新执行？


感谢回复，更换打码平台之后问题解决

**Comment by Cxy-2008** [comment]
> > 尝试重新执行？
> 
> 
> 感谢回复，更换打码平台之后问题解决

大佬 问一下如何更换打码平台
