### ISSUE TITLE
mihoyobbs_salt这个是咋拿到的，劳达。

### ISSUE THREAD

**Issue by tuotuooo** [Womsxd/MihoyoBBSTools#148]

**Comment by BTMuli** [comment]
<details>
<summary>What I can say</summary>

~~当然是米奇妙妙工具了~~

</details>

**Comment by lulu666lulu** [comment]
![image](https://github.com/Womsxd/MihoyoBBSTools/assets/69200009/9acaf9f4-bb7c-4ad6-8274-89266ba5fde3)

**Comment by lulu666lulu** [comment]
![4266bab0c34a15069a5a226ed37071df](https://github.com/Womsxd/MihoyoBBSTools/assets/69200009/19766261-cb94-409c-87e6-05b06bf68c55)

**Comment by BTMuli** [comment]
https://github.com/UIGF-org/mihoyo-api-collect/issues/1

**Comment by Masterain98** [comment]
一般是托梦得知的

**Comment by Womsxd** [comment]
从其他米游社项目抄的

**Comment by tuotuooo** [comment]
Masterain98   GitHub人均幽默风😂

**Comment by tuotuooo** [comment]
github上的人都这么幽默的吗🤣

**Comment by tuotuooo** [comment]
> [UIGF-org/mihoyo-api-collect#1](https://github.com/UIGF-org/mihoyo-api-collect/issues/1)

还有糕手？🐂的

**Comment by tuotuooo** [comment]
> > [UIGF-org/mihoyo-api-collect#1](https://github.com/UIGF-org/mihoyo-api-collect/issues/1)
> 
> 还有糕手？🐂的

这是初中生？？我初中还在打CF玩躲猫猫🫠
