### ISSUE TITLE
在开启bbs功能后报错KeyError: 'login_ticket'

### ISSUE THREAD

**Issue by hcv2** [Womsxd/MihoyoBBSTools#154]
在开启bbs功能后报错：
Traceback (most recent call last):
  File "D:\桌面\MihoyoBBSTools-master\main_multi.py", line 96, in <module>
    main_multi(autorun_flag)
  File "D:\桌面\MihoyoBBSTools-master\main_multi.py", line 62, in main_multi
    run_code, run_message = main.main()
                            ^^^^^^^^^^^
  File "D:\桌面\MihoyoBBSTools-master\main.py", line 37, in main
    login.login()
  File "D:\桌面\MihoyoBBSTools-master\login.py", line 29, in login
    uid = get_uid()
          ^^^^^^^^^
  File "D:\桌面\MihoyoBBSTools-master\login.py", line 59, in get_uid
    params={"login_ticket": config.config["account"]["login_ticket"]},
                            ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'login_ticket'
但在关闭后可以使用

**Comment by Womsxd** [comment]
抓的cookie缺少Uid了，加上历史遗留问题

**Comment by hcv2** [comment]
额是miyoushe.com-cookie里的uid吗

**Comment by Womsxd** [comment]
是的，就是account_id，ltuid，login_uid这三个后面跟着的数字

**Comment by hcv2** [comment]
> 是的，就是account_id，ltuid，login_uid这三个后面跟着的数字

我并没有在miyoushe.com里的cookie找到login_uid

**Comment by Womsxd** [comment]
ltuid，ltuid_v2，account_id_v2


> > 是的，就是account_id，ltuid，login_uid这三个后面跟着的数字
> 
> 我并没有在miyoushe.com里的cookie找到login_uid

这些都没有嘛？

**Comment by Womsxd** [comment]
> > ltuid，ltuid_v2，account_id_v2
> > > > 是的，就是account_id，ltuid，login_uid这三个后面跟着的数字
> > > 
> > > 
> > > 我并没有在 miyoushe.com 里的cookie找到login_uid
> > 
> > 
> > 这些都没有嘛？
> 
> account_id，ltuid有

那先请你手动复制这里面的数字，粘贴到配置文件的 stuid 项目上，示例：stuid: '123465'

**Comment by hcv2** [comment]
> > > ltuid，ltuid_v2，account_id_v2
> > > > > 是的，就是account_id，ltuid，login_uid这三个后面跟着的数字
> > > > 
> > > > 
> > > > 我并没有在 miyoushe.com 里的 cookie找到login_uid
> > > 
> > > 
> > > 这些都没有嘛？
> > 
> > 
> > account_id，ltuid有
> 
> 那先请你手动复制这里面的数字，粘贴到配置文件的 stuid 项目上，示例：stuid： '123465'

吧stuid和mid粘贴上后可以运行了

**Comment by Womsxd** [comment]
莫名其妙的bug喜加一还是特殊情况，有带观察(

**Comment by hcv2** [comment]
> 莫名其妙的bug喜加一还是特殊情况，有带观察（

获取了3次了cookie这玩意一直过期😅

**Comment by NNuuNN** [comment]
按照[获取Stoken](https://github.com/Womsxd/mihoyo_login)项目获取stoken贴上，并按照上面步骤粘贴了stuid后，提示cookies过期
