### ISSUE TITLE
青龙面板执行错误

### ISSUE THREAD

**Issue by windskyxb** [Womsxd/MihoyoBBSTools#17]
![image](https://user-images.githubusercontent.com/60282327/226153365-fb1d19de-0354-458e-9826-805720aa0d84.png)
已在青龙面板环境变量中添加AutoMihoyoBBS_config_path变量并启用，值为/ql/data/config/
但删除或禁用AutoMihoyoBBS_config_path变量却能正常运行

**Comment by ShanshanHY** [comment]
> ![image](https://user-images.githubusercontent.com/60282327/226153365-fb1d19de-0354-458e-9826-805720aa0d84.png) 已在青龙面板环境变量中添加AutoMihoyoBBS_config_path变量并启用，值为/ql/data/config/ 但删除或禁用AutoMihoyoBBS_config_path变量却能正常运行

你这个添加的有问题吧，看图中你添加的是`ql/data/config/`，而不是`/ql/data/config/`
![image](https://user-images.githubusercontent.com/29966961/227765897-453bb2f4-ce52-4aa3-897c-4e241e5d8d9f.png)

**Comment by windskyxb** [comment]
> > ![image](https://user-images.githubusercontent.com/60282327/226153365-fb1d19de-0354-458e-9826-805720aa0d84.png) 已在青龙面板环境变量中添加AutoMihoyoBBS_config_path变量并启用，值为/ql/data/config/ 但删除或禁用AutoMihoyoBBS_config_path变量却能正常运行
> 
> 你这个添加的有问题吧，看图中你添加的是`ql/data/config/`，而不是`/ql/data/config/` ![image](https://user-images.githubusercontent.com/29966961/227765897-453bb2f4-ce52-4aa3-897c-4e241e5d8d9f.png)



> > ![image](https://user-images.githubusercontent.com/60282327/226153365-fb1d19de-0354-458e-9826-805720aa0d84.png) 已在青龙面板环境变量中添加AutoMihoyoBBS_config_path变量并启用，值为/ql/data/config/ 但删除或禁用AutoMihoyoBBS_config_path变量却能正常运行
> 
> 你这个添加的有问题吧，看图中你添加的是`ql/data/config/`，而不是`/ql/data/config/` ![image](https://user-images.githubusercontent.com/29966961/227765897-453bb2f4-ce52-4aa3-897c-4e241e5d8d9f.png)

确实(ˉ▽ˉ；)...
