### ISSUE TITLE
[bug] 签到时候名字非常规字符时会导致报错并将cookie清除

### ISSUE THREAD

**Issue by wdvipa** [Womsxd/MihoyoBBSTools#170]
![image](https://github.com/Womsxd/MihoyoBBSTools/assets/104631880/3ef700e8-07bf-4f44-b317-e043c0292632)

**Comment by Womsxd** [comment]
log是不是开启了记录到文件的情况？

**Comment by wdvipa** [comment]
应该不是，经测试青龙面板也一样
![image](https://github.com/Womsxd/MihoyoBBSTools/assets/104631880/ee7af530-9021-444c-9a06-26dd1ce61990)
