### ISSUE TITLE
获取米游社cookies那一块貌似有问题？

### ISSUE THREAD

**Issue by ZakiuC** [Womsxd/MihoyoBBSTools#174]
readme里说从cookie_token_v2往后复制，脚本会报错没有uid,如图：
![微信图片_20240712162655](https://github.com/user-attachments/assets/d22006be-87ff-4832-8b88-1c28a8f2518e)
然后我把整个Cookie都复制下来就可以了，所以是readme没更新吗？

**Comment by Womsxd** [comment]
应该该更新了

**Comment by y785201595** [comment]
我不管怎么获取都是cookie错误
2024-07-13T14:44:54 INFO Config加载完毕
2024-07-13T14:44:54 ERROR 无Stoken 请手动填入stoken!
2024-07-13T14:44:54 ERROR 账号Cookie有问题！
米游社-Cookie错误

账号Cookie出错！

**Comment by Womsxd** [comment]
> 我不管怎么获取都是cookie错误 2024-07-13T14:44:54 INFO Config加载完毕 2024-07-13T14:44:54 ERROR 无Stoken 请手动填入stoken! 2024-07-13T14:44:54 ERROR 账号Cookie有问题！ 米游社-Cookie错误
> 
> 账号Cookie出错！

https://github.com/Womsxd/MihoyoBBSTools?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E7%A8%8B%E5%BA%8F 看 这一步 https://github.com/Womsxd/MihoyoBBSTools?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E7%A8%8B%E5%BA%8F

**Comment by xuehantian** [comment]
> > 我不管怎么获取都是cookie错误 2024-07-13T14:44:54 INFO Config加载完毕 2024-07-13T14:44:54 ERROR 无Stoken 请手动填入stoken! 2024-07-13T14:44:54 ERROR 账号Cookie有问题！ 米游社-Cookie错误
> > 账号Cookie出错！
> 
> 看readme的 通过 获取Stoken 项目获取Stoken

大佬，我用那个项目在扫码前一直提示我“等待扫码”，我用“米游社”扫码的瞬间就会弹出错误：TypeError: 'NoneType' object is not subscriptable。
我自己排查一下好像是："响应 JSON 不包含 'data' 或 'data' 为 None"，这是为什么呢？

**Comment by Womsxd** [comment]
> > > 我不管怎么获取都是cookie错误 2024-07-13T14:44:54 INFO Config加载完毕 2024-07-13T14:44:54 ERROR 无Stoken 请手动填入stoken! 2024-07-13T14:44:54 ERROR 账号Cookie有问题！ 米游社-Cookie错误
> > > 账号Cookie出错！
> > 
> > 
> > 看readme的 通过 获取Stoken 项目获取Stoken
> 
> 大佬，我用那个项目在扫码前一直提示我“等待扫码”，我用“米游社”扫码的瞬间就会弹出错误：TypeError: 'NoneType' object is not subscriptable。 我自己排查一下好像是："响应 JSON 不包含 'data' 或 'data' 为 None"，这是为什么呢？

残废了，建议先关闭bbs功能
