### ISSUE TITLE
config.yaml路径问题

### ISSUE THREAD

**Issue by YanHanYe** [Womsxd/MihoyoBBSTools#175]
我是部署在linux的青龙面板下的，已经将文件放在指定路径下并且777了，但是仍然报错。
![image](https://github.com/user-attachments/assets/122ed4e8-dd9a-4486-91d4-5ffc681ef28c)
![image](https://github.com/user-attachments/assets/d4daa70f-93d8-47ee-b57e-e026847a8b97)
![image](https://github.com/user-attachments/assets/dfec475b-8000-4401-82f0-e2ba773c40a5)

**Comment by yuxian158** [comment]
这个需要在容器里面编辑

**Comment by YanHanYe** [comment]
容器里已经编辑过了，就是通过环境变量修改的发自我的手机-------- 原始邮件 --------发件人： 余弦 ***@***.***>日期： 2024年7月16日周二 15:06收件人： Womsxd/MihoyoBBSTools ***@***.***>抄送： YanHanYe ***@***.***>, Author ***@***.***>主    题： Re: [Womsxd/MihoyoBBSTools] config.yaml路径问题 (Issue #175)
这个需要在容器里面编辑

**Comment by Womsxd** [comment]
找不到文件，是在ql容器里面了么？

**Comment by YanHanYe** [comment]
已经解决了，在电报问赞助码的是我发自我的手机-------- 原始邮件 --------发件人： Womsxd ***@***.***>日期： 2024年7月16日周二 21:21收件人： Womsxd/MihoyoBBSTools ***@***.***>抄送： YanHanYe ***@***.***>, Author ***@***.***>主    题： Re: [Womsxd/MihoyoBBSTools] config.yaml路径问题 (Issue #175)
找不到文件，是在ql容器里面了么？
