### ISSUE TITLE
海外版绝区零签到问题

### ISSUE THREAD

**Issue by dxx101** [Womsxd/MihoyoBBSTools#176]
<html>
<body>

date | stream | content
-- | -- | --
2024/07/16 16:41:53 | stdout | 2024-07-16T16:41:53 INFO Next run datetime: 2024-07-17 06:30:18
2024/07/16 16:41:53 | stdout | 2024-07-16T16:41:53 INFO Current running datetime: 2024-07-16 16:41:53
2024/07/16 16:41:53 | stdout | AttributeError: 'NoneType' object has no attribute 'get'
2024/07/16 16:41:53 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/07/16 16:41:53 | stdout | today = info_list.get("data", {}).get("today")
2024/07/16 16:41:53 | stdout | File "/var/app/hoyo_checkin.py", line 38, in hoyo_checkin
2024/07/16 16:41:53 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/07/16 16:41:53 | stdout | ret_msg = '绝区零:\n' + hoyo_checkin("https://sg-act-nap-api.hoyolab.com/event/luna/zzz/os",
2024/07/16 16:41:53 | stdout | File "/var/app/hoyo_checkin.py", line 118, in zzz
2024/07/16 16:41:53 | stdout | ^^^^^^^^^^^^^^^^^
2024/07/16 16:41:53 | stdout | ret_msg += f"\n\n{globals()[game]()}"
2024/07/16 16:41:53 | stdout | File "/var/app/hoyo_checkin.py", line 136, in run_task
2024/07/16 16:41:53 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^
2024/07/16 16:41:53 | stdout | os_result = hoyo_checkin.run_task()
2024/07/16 16:41:53 | stdout | File "/var/app/main.py", line 52, in main
2024/07/16 16:41:53 | stdout | ^^^^^^^^^^^
2024/07/16 16:41:53 | stdout | run_code, run_message = main.main()
2024/07/16 16:41:53 | stdout | File "/var/app/./main_multi.py", line 62, in main_multi
2024/07/16 16:41:53 | stdout | main_multi(autorun_flag)
2024/07/16 16:41:53 | stdout | File "/var/app/./main_multi.py", line 96, in <module>
2024/07/16 16:41:53 | stdout | Traceback (most recent call last):
2024/07/16 16:41:22 | stdout | 2024-07-16T16:41:22 INFO 正在进行绝区零签到
2024/07/16 16:41:22 | stdout | 2024-07-16T16:41:22 INFO 海外版:
2024/07/16 16:41:22 | stdout | 2024-07-16T16:41:22 INFO Config加载完毕
2024/07/16 16:41:22 | stdout | 2024-07-16T16:41:22 INFO 正在执行hoyolab1.yaml
2024/07/16 16:41:22 | stdout | 2024-07-16T16:41:22 INFO 已搜索到1个配置文件，正在开始执行！
2024/07/16 16:41:22 | stdout | 2024-07-16T16:41:22 INFO 正在搜索配置文件！
2024/07/16 16:41:22 | stdout | 2024-07-16T16:41:22 INFO AutoMihoyoBBS Multi User mode
2024/07/16 16:41:22 | stdout | 2024-07-16T16:41:22 INFO Starting signing
2024/07/16 16:41:22 | stdout | 2024-07-16T16:41:22 INFO 使用DOCKER运行米游社签到

请问大佬这是什么问题，同样设置下国服就可以用

**Comment by dxx101** [comment]
<html>
<body>

date | stream | content
-- | -- | --
2024/07/16 16:41:53 | stdout | 2024-07-16T16:41:53 INFO Next run datetime: 2024-07-17 06:30:18

2024/07/16 16:41:53 | stdout | 2024-07-16T16:41:53 INFO Current running datetime: 2024-07-16 16:41:53

2024/07/16 16:41:53 | stdout | AttributeError: 'NoneType' object has no attribute 'get'

2024/07/16 16:41:53 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024/07/16 16:41:53 | stdout | today = info_list.get("data", {}).get("today")

2024/07/16 16:41:53 | stdout | File "/var/app/hoyo_checkin.py", line 38, in hoyo_checkin

2024/07/16 16:41:53 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024/07/16 16:41:53 | stdout | ret_msg = '绝区零:\n' + hoyo_checkin("https://sg-act-nap-api.hoyolab.com/event/luna/zzz/os",

2024/07/16 16:41:53 | stdout | File "/var/app/hoyo_checkin.py", line 118, in zzz

2024/07/16 16:41:53 | stdout | ^^^^^^^^^^^^^^^^^

2024/07/16 16:41:53 | stdout | ret_msg += f"\n\n{globals()[game]()}"

2024/07/16 16:41:53 | stdout | File "/var/app/hoyo_checkin.py", line 136, in run_task

2024/07/16 16:41:53 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^

2024/07/16 16:41:53 | stdout | os_result = hoyo_checkin.run_task()

2024/07/16 16:41:53 | stdout | File "/var/app/main.py", line 52, in main

2024/07/16 16:41:53 | stdout | ^^^^^^^^^^^

2024/07/16 16:41:53 | stdout | run_code, run_message = main.main()

2024/07/16 16:41:53 | stdout | File "/var/app/./main_multi.py", line 62, in main_multi

2024/07/16 16:41:53 | stdout | main_multi(autorun_flag)

2024/07/16 16:41:53 | stdout | File "/var/app/./main_multi.py", line 96, in <module>

2024/07/16 16:41:53 | stdout | Traceback (most recent call last):

2024/07/16 16:41:22 | stdout | 2024-07-16T16:41:22 INFO 正在进行绝区零签到

2024/07/16 16:41:22 | stdout | 2024-07-16T16:41:22 INFO 海外版:

2024/07/16 16:41:22 | stdout | 2024-07-16T16:41:22 INFO Config加载完毕

2024/07/16 16:41:22 | stdout | 2024-07-16T16:41:22 INFO 正在执行hoyolab1.yaml

2024/07/16 16:41:22 | stdout | 2024-07-16T16:41:22 INFO 已搜索到1个配置文件，正在开始执行！

2024/07/16 16:41:22 | stdout | 2024-07-16T16:41:22 INFO 正在搜索配置文件！

2024/07/16 16:41:22 | stdout | 2024-07-16T16:41:22 INFO AutoMihoyoBBS Multi User mode

2024/07/16 16:41:22 | stdout | 2024-07-16T16:41:22 INFO Starting signing

2024/07/16 16:41:22 | stdout | 2024-07-16T16:41:22 INFO 使用DOCKER运行米游社签到



</body>
</html>

**Comment by Womsxd** [comment]
更新一下？可能你用的版本是只支持国服的，国际服是在国服支持后第二天才支持
