### ISSUE TITLE
> def bbs_captcha(gt: str, challenge: str):

### ISSUE THREAD

**Issue by w211691** [Womsxd/MihoyoBBSTools#178]
> def bbs_captcha(gt: str, challenge: str):
> rep = http.post(
> url= "http://api.rrocr.com/api/recognize.html",
> data={
> "appkey": "你自己的appkey",
> "gt": gt,
> "challenge" : challenge,
> "referer" : "https://bbs-api.miyoushe.com/apihub/app/api/signIn"
> }
> ).json()
> return rep["data"]["validate"]

兄弟，这个错误解决了吗？

_Originally posted by @xuehantian in https://github.com/Womsxd/MihoyoBBSTools/issues/95#issuecomment-2233800677_

解决了，请了另外会Python的兄弟帮忙弄了，代码如下:

def game_captcha(gt: str, challenge: str):
    rep = http.post(
       url= "http://api.rrocr.com/api/recognize.html",
       data={
           "appkey": "你的key",
           "gt": gt,
           "challenge" : challenge,
           "referer" : "https://bbs-api.miyoushe.com/apihub/app/api/signIn"
           },timeout=180).json()
    return rep["data"]["validate"]

def bbs_captcha(gt: str, challenge: str):
    rep = http.post(
       url= "http://api.rrocr.com/api/recognize.html",
       data={
           "appkey": "你的key",
           "gt": gt,
           "challenge" : challenge,
           "referer" : "https://bbs-api.miyoushe.com/apihub/app/api/signIn"
           },timeout=180).json()
    return rep["data"]["validate"]
   
另外人人打码已经倒闭了，等手头剩下的次数用完就该换其他家了。。。。

**Comment by xuehantian** [comment]
好的，谢了兄弟。我这里昨天也成功了。人人打码我登录不上去，我另外找了一个支持极验打码的平台，叫套套图像打码。我自己对着别人的程序修改了一下也能使用。
import time
from request import http


# def game_captcha(gt: str, challenge: str):
#     return None  # 失败返回None 成功返回validate
def game_captcha(gt: str, challenge: str):
    rep = http.post(
        url= "http://api.ttocr.com/api/recognize",
        data={
            "appkey": "",
            "gt": gt,
            "challenge" : challenge,
            "referer" : "https://api-takumi.mihoyo.com/event/luna/sign",
            "itemid" :   388
        }
    ).json()
    # return rep["data"]["validate"]

    # rep2 = http.post(
    #     url= "http://api.ttocr.com/api/results",
    #     data={
    #         "appkey": "ede5885bb9432b1232f053b89be0c38a",
    #         "resultid": str(rep["resultid"]),
    #     },
    #     timeout = (60, 60),
    # ).json()


    max_wait_time = 60  # 最大等待时间
    interval = 5  # 轮询间隔时间

    start_time = time.time()
    while time.time() - start_time < max_wait_time:
        try:
            rep2 = http.post(
                url="http://api.ttocr.com/api/results",
                data={
                    "appkey": "",
                    "resultid": str(rep["resultid"]),
                },
                timeout=(60, 60)  # 设置连接超时和读取超时均为60秒
            ).json()

            if rep2.get("status") == 2:
                print("等待识别结果...")
                time.sleep(interval)  # 等待一段时间后再次发送请求
            else:
                print("API Response:", rep)
                print("API Response:", str(rep["resultid"]))
                print("API Response2:", rep2)
                return rep2["data"]["validate"]

        except rep2.exceptions.Timeout:
            print("请求超时")
            return None
        except rep2.exceptions.RequestException as e:
            print(f"请求发生错误: {e}")
            return None

    print("超过最大等待时间，未获取到结果")
    return None



梦心
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Womsxd/MihoyoBBSTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月18日(星期四) 上午10:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;[Womsxd/MihoyoBBSTools] &gt; def bbs_captcha(gt: str, challenge: str): (Issue #178)





           &gt; def bbs_captcha(gt: str, challenge: str):   
rep = http.post(
 url= "http://api.rrocr.com/api/recognize.html",
 data={
 "appkey": "你自己的appkey",
 "gt": gt,
 "challenge" : challenge,
 "referer" : "https://bbs-api.miyoushe.com/apihub/app/api/signIn"
 }
 ).json()
 return rep["data"]["validate"]
  
兄弟，这个错误解决了吗？
 
Originally posted by @xuehantian in #95 (comment)
 
解决了，请了另外会Python的兄弟帮忙弄了，代码如下:
 
def game_captcha(gt: str, challenge: str):
 rep = http.post(
 url= "http://api.rrocr.com/api/recognize.html",
 data={
 "appkey": "你的key",
 "gt": gt,
 "challenge" : challenge,
 "referer" : "https://bbs-api.miyoushe.com/apihub/app/api/signIn"
 },timeout=180).json()
 return rep["data"]["validate"]
 
def bbs_captcha(gt: str, challenge: str):
 rep = http.post(
 url= "http://api.rrocr.com/api/recognize.html",
 data={
 "appkey": "你的key",
 "gt": gt,
 "challenge" : challenge,
 "referer" : "https://bbs-api.miyoushe.com/apihub/app/api/signIn"
 },timeout=180).json()
 return rep["data"]["validate"]
 
另外人人打码已经倒闭了，等手头剩下的次数用完就该换其他家了。。。。

**Comment by xuehantian** [comment]
还有兄弟，你那里可以签到米游币吗，我这里用作者的代码获取不到米游社的stoken。一直显示如下错误：
Traceback (most recent call last):
&nbsp; File "D:\Python_study\miyoushe\mihoyo_login-st\qr_login.py", line 211, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "D:\Python_study\miyoushe\mihoyo_login-st\qr_login.py", line 205, in main
&nbsp; &nbsp; uid, game_token = check_login(app_id, ticket, device)
&nbsp; File "D:\Python_study\miyoushe\mihoyo_login-st\qr_login.py", line 148, in check_login
&nbsp; &nbsp; if data["stat"] == "Init":
TypeError: 'NoneType' object is not subscriptable





梦心
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Womsxd/MihoyoBBSTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月18日(星期四) 上午10:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;[Womsxd/MihoyoBBSTools] &gt; def bbs_captcha(gt: str, challenge: str): (Issue #178)





           &gt; def bbs_captcha(gt: str, challenge: str):   
rep = http.post(
 url= "http://api.rrocr.com/api/recognize.html",
 data={
 "appkey": "你自己的appkey",
 "gt": gt,
 "challenge" : challenge,
 "referer" : "https://bbs-api.miyoushe.com/apihub/app/api/signIn"
 }
 ).json()
 return rep["data"]["validate"]
  
兄弟，这个错误解决了吗？
 
Originally posted by @xuehantian in #95 (comment)
 
解决了，请了另外会Python的兄弟帮忙弄了，代码如下:
 
def game_captcha(gt: str, challenge: str):
 rep = http.post(
 url= "http://api.rrocr.com/api/recognize.html",
 data={
 "appkey": "你的key",
 "gt": gt,
 "challenge" : challenge,
 "referer" : "https://bbs-api.miyoushe.com/apihub/app/api/signIn"
 },timeout=180).json()
 return rep["data"]["validate"]
 
def bbs_captcha(gt: str, challenge: str):
 rep = http.post(
 url= "http://api.rrocr.com/api/recognize.html",
 data={
 "appkey": "你的key",
 "gt": gt,
 "challenge" : challenge,
 "referer" : "https://bbs-api.miyoushe.com/apihub/app/api/signIn"
 },timeout=180).json()
 return rep["data"]["validate"]
 
另外人人打码已经倒闭了，等手头剩下的次数用完就该换其他家了。。。。

**Comment by w211691** [comment]
> 还有兄弟，你那里可以签到米游币吗，我这里用作者的代码获取不到米游社的stoken。一直显示如下错误： Traceback (most recent call last): &nbsp; File "D:\Python_study\miyoushe\mihoyo_login-st\qr_login.py", line 211, in <module&gt; &nbsp; &nbsp; main() &nbsp; File "D:\Python_study\miyoushe\mihoyo_login-st\qr_login.py", line 205, in main &nbsp; &nbsp; uid, game_token = check_login(app_id, ticket, device) &nbsp; File "D:\Python_study\miyoushe\mihoyo_login-st\qr_login.py", line 148, in check_login &nbsp; &nbsp; if data["stat"] == "Init": TypeError: 'NoneType' object is not subscriptable 梦心 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Womsxd/MihoyoBBSTools" ***@***.***&gt;; 发送时间:&nbsp;2024年7月18日(星期四) 上午10:40 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;[Womsxd/MihoyoBBSTools] &gt; def bbs_captcha(gt: str, challenge: str): (Issue #178) &gt; def bbs_captcha(gt: str, challenge: str): rep = http.post( url= "http://api.rrocr.com/api/recognize.html", data={ "appkey": "你自己的appkey", "gt": gt, "challenge" : challenge, "referer" : "https://bbs-api.miyoushe.com/apihub/app/api/signIn" } ).json() return rep["data"]["validate"] 兄弟，这个错误解决了吗？ Originally posted by @xuehantian in #95 (comment) 解决了，请了另外会Python的兄弟帮忙弄了，代码如下: def game_captcha(gt: str, challenge: str): rep = http.post( url= "http://api.rrocr.com/api/recognize.html", data={ "appkey": "你的key", "gt": gt, "challenge" : challenge, "referer" : "https://bbs-api.miyoushe.com/apihub/app/api/signIn" },timeout=180).json() return rep["data"]["validate"] def bbs_captcha(gt: str, challenge: str): rep = http.post( url= "http://api.rrocr.com/api/recognize.html", data={ "appkey": "你的key", "gt": gt, "challenge" : challenge, "referer" : "https://bbs-api.miyoushe.com/apihub/app/api/signIn" },timeout=180).json() return rep["data"]["validate"] 另外人人打码已经倒闭了，等手头剩下的次数用完就该换其他家了。。。。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

我倒是可以，就是今天绝区零签到报错，不知道什么情况

**Comment by dxx101** [comment]
![QQ截图20240719082101](https://github.com/user-attachments/assets/b1ae4d3b-61d4-4aec-bbac-48a834610974)
![QQ截图20240719082221](https://github.com/user-attachments/assets/e22d602d-23f9-49c5-b5a6-1cbd626dcdb9)

大佬，能麻烦您帮我看一下我这个哪里有问题吗

**Comment by w211691** [comment]
> ![QQ截图20240719082101](https://private-user-images.githubusercontent.com/74139097/350179794-b1ae4d3b-61d4-4aec-bbac-48a834610974.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTEzNTgsIm5iZiI6MTcyMTM1MTA1OCwicGF0aCI6Ii83NDEzOTA5Ny8zNTAxNzk3OTQtYjFhZTRkM2ItNjFkNC00YWVjLWJiYWMtNDhhODM0NjEwOTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAxMDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NzhhNWI3YTI1ZTFiNjNjZmEyZGI5MTcxZTkyYjVmNjg2MzBhOGMyMTNhMGI0Mzc1ZDZkMjViZDU4YTk1NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v5Zh7t7e83FYg3BWkX71KuluOl8Y9GqRP0VxQalymFQ) ![QQ截图20240719082221](https://private-user-images.githubusercontent.com/74139097/350179918-e22d602d-23f9-49c5-b5a6-1cbd626dcdb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTEzNTgsIm5iZiI6MTcyMTM1MTA1OCwicGF0aCI6Ii83NDEzOTA5Ny8zNTAxNzk5MTgtZTIyZDYwMmQtMjNmOS00OWM1LWI1YTYtMWNiZDYyNmRjZGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAxMDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZmJiYzE2MjBlMjk3YzBhNjllMDNjNTUwMjg4OWY4ZGYyYTFjNzFmYjEyYTg0NWIxNTE3NDUyMTJhZjZlYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MOIUSkYUwaAA7hIOGWVXflo5aRsNjhXyMX9MeuVxwFw)
> 
> 大佬，能麻烦您帮我看一下我这个哪里有问题吗

一样的报错，看来米游社换验证配置了

**Comment by w211691** [comment]
> ![QQ截图20240719082101](https://private-user-images.githubusercontent.com/74139097/350179794-b1ae4d3b-61d4-4aec-bbac-48a834610974.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTI0MzAsIm5iZiI6MTcyMTM1MjEzMCwicGF0aCI6Ii83NDEzOTA5Ny8zNTAxNzk3OTQtYjFhZTRkM2ItNjFkNC00YWVjLWJiYWMtNDhhODM0NjEwOTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAxMjIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NjVmY2M4MDA3ZmQ2MmM5YjQxYjZmY2U5MDdlM2I0ZDRlNzJmZTdjMTZhZDE3ZTVkMDI1MGM3MTcxZWNmMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N1oyj0Dg75_4pVYn5bbIOXfTyLyDs7vnNhvJZQyi-vI) ![QQ截图20240719082221](https://private-user-images.githubusercontent.com/74139097/350179918-e22d602d-23f9-49c5-b5a6-1cbd626dcdb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTI0MzAsIm5iZiI6MTcyMTM1MjEzMCwicGF0aCI6Ii83NDEzOTA5Ny8zNTAxNzk5MTgtZTIyZDYwMmQtMjNmOS00OWM1LWI1YTYtMWNiZDYyNmRjZGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAxMjIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NTMyMGY3OWEwOWFiMDQyNzMwMGU1ZmI4NzI2YTQ0MTMxOTk0M2RmY2IxYWMxY2UwYjIzZTY2NzJhYzdjYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2gpZae73HvGE7HR-NdtwBLYJb9ck2oOL_NdslJMfhXw)
> 
> 大佬，能麻烦您帮我看一下我这个哪里有问题吗

![image](https://github.com/user-attachments/assets/dd8fac75-bdb8-47e1-9130-51274c618003)

照着这样改吧，我昨天瞎弄搞坏了，今天改了改好了

**Comment by Womsxd** [comment]
> ![QQ截图20240719082101](https://private-user-images.githubusercontent.com/74139097/350179794-b1ae4d3b-61d4-4aec-bbac-48a834610974.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTIyNzAsIm5iZiI6MTcyMTM1MTk3MCwicGF0aCI6Ii83NDEzOTA5Ny8zNTAxNzk3OTQtYjFhZTRkM2ItNjFkNC00YWVjLWJiYWMtNDhhODM0NjEwOTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAxMTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NzM4ZWE0ZWQ0MTkzYzA4MzY4OWEwZDQ4MGQ1YTVkNWJjODJlYmNlYTA3NDljN2E0YjBhYWJiNGJjOTk4NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.muLzuUNSOu37lGMjRoScBJoAU547iV3x11icVepGh-E) ![QQ截图20240719082221](https://private-user-images.githubusercontent.com/74139097/350179918-e22d602d-23f9-49c5-b5a6-1cbd626dcdb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTIyNzAsIm5iZiI6MTcyMTM1MTk3MCwicGF0aCI6Ii83NDEzOTA5Ny8zNTAxNzk5MTgtZTIyZDYwMmQtMjNmOS00OWM1LWI1YTYtMWNiZDYyNmRjZGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAxMTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMWI2NGZhZDcwOTQwOTI5NzE5NDJhNDU4MDBiZWRlOTQwNzI0OWFhMjgwNTcwNWVjMjBjY2Y4ZjA1ODA5ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ow-E5opZVzb_i6kQdiLZJ1fJOpa2ft5fZQFNnvYUGNs)
> 
> 大佬，能麻烦您帮我看一下我这个哪里有问题吗

打码接口炸了
