### ISSUE TITLE
大佬，触发验证码，签到失败怎么攻克

### ISSUE THREAD

**Issue by chendada777** [Womsxd/MihoyoBBSTools#186]
2024-08-14T03:49:35 INFO 脚本执行完毕，共执行1个配置文件，成功0个，没执行0个，失败0个
--
2024/08/14 03:49:35 | stdout |  
2024/08/14 03:49:26 | stdout | 2024-08-14T03:49:26 INFO config.yaml执行完毕
2024/08/14 03:49:26 | stdout | json信息:{"retcode":0,"message":"OK","data":{"code":"","risk_code":5001,"gt":"bd4331e976b868","challenge":"892cc32c","success":1,"is_risk":true}}
2024/08/14 03:49:26 | stdout | 2024-08-14T03:49:26 WARNING 账号签到失败！原因: 验证码
2024/08/14 03:49:26 | stdout | 2024-08-14T03:49:26 INFO 触发验证码，即将进行第 3 次重试，最多 3 次
2024/08/14 03:49:10 | stdout | 2024-08-14T03:49:10 INFO 触发验证码，即将进行第 2 次重试，最多 3 次
2024/08/14 03:48:48 | stdout | 2024-08-14T03:48:48 INFO 正在为绳匠是玲进行签到...
2024/08/14 03:48:48 | stdout | 2024-08-14T03:48:48 INFO 正在获取签到奖励列表...
2024/08/14 03:48:48 | stdout | 2024-08-14T03:48:48 INFO 已获取到1个绝区零账号信息
2024/08/14 03:48:47 | stdout | 2024-08-14T03:48:47 INFO 正在获取米哈游账号绑定的绝区零账号列表...
2024/08/14 03:48:47 | stdout | 2024-08-14T03:48:47 INFO 正在进行绝区零签到
2024/08/14 03:48:40 | stdout | json信息:{"retcode":0,"message":"OK","data":{"code":"","risk_code":5001,"gt":"afa6ce8","challenge":"18a953937a17cd72","success":1,"is_risk":true}}
2024/08/14 03:48:40 | stdout | 2024-08-14T03:48:40 WARNING 账号签到失败！原因: 验证码
2024/08/14 03:48:40 | stdout | 2024-08-14T03:48:40 INFO 触发验证码，即将进行第 3 次重试，最多 3 次
2024/08/14 03:48:29 | stdout | 2024-08-14T03:48:29 INFO 触发验证码，即将进行第 2 次重试，最多 3 次
2024/08/14 03:48:09 | stdout | 2024-08-14T03:48:09 INFO 正在为开拓者进行签到...
2024/08/14 03:48:09 | stdout | 2024-08-14T03:48:09 INFO 正在获取签到奖励列表...
2024/08/14 03:48:09 | stdout | 2024-08-14T03:48:09 INFO 已获取到1个崩坏： 星穹铁道账号信息
2024/08/14 03:48:08 | stdout | 2024-08-14T03:48:08 INFO 正在获取米哈游账号绑定的崩坏： 星穹铁道账号列表...
2024/08/14 03:48:08 | stdout | 2024-08-14T03:48:08 INFO 正在进行崩坏: 星穹铁道签到
2024/08/14 03:48:05 | stdout | 今天获得的奖励是冒险家的经验x2
2024/08/14 03:48:05 | stdout | 2024-08-14T03:48:05 INFO 旅行者今天已经签到过了~
2024/08/14 03:47:59 | stdout | 2024-08-14T03:47:59 INFO 正在为旅行者进行签到...
2024/08/14 03:47:59 | stdout | 2024-08-14T03:47:59 INFO 正在获取签到奖励列表...
2024/08/14 03:47:59 | stdout | 2024-08-14T03:47:59 INFO 已获取到1个原神账号信息
2024/08/14 03:47:58 | stdout | 2024-08-14T03:47:58 INFO 正在获取米哈游账号绑定的原神账号列表...
2024/08/14 03:47:58 | stdout | 2024-08-14T03:47:58 INFO 正在进行原神签到
2024/08/14 03:47:51 | stdout | 2024-08-14T03:47:51 INFO Config加载完毕
2024/08/14 03:47:51 | stdout | 2024-08-14T03:47:51 INFO 正在执行config.yaml
2024/08/14 03:47:51 | stdout | 2024-08-14T03:47:51 INFO 已搜索到1个配置文件，正在开始执行！
2024/08/14 03:47:51 | stdout | 2024-08-14T03:47:51 INFO 正在搜索配置文件！
2024/08/14 03:47:51 | stdout | 2024-08-14T03:47:51 INFO AutoMihoyoBBS Multi User mode
2024/08/14 03:47:51 | stdout | 2024-08-14T03:47:51 INFO Starting signing
2024/08/14 03:47:51 | stdout | 2024-08-14T03:47:51 INFO 使用DOCKER运行米游社签到

**Comment by Womsxd** [comment]
对接打码平台。预留位置：captcha.py
