### ISSUE TITLE
cqhttp推送存在access_token鉴权时无法正常推送

### ISSUE THREAD

**Issue by Mei-Sakura** [Womsxd/MihoyoBBSTools#191]
请为cqhttp推送添加access_token鉴权选项

**Comment by Womsxd** [comment]
可以在url部分配置access_token鉴权

**Comment by Womsxd** [comment]
[onebot-11文档](https://github.com/botuniverse/onebot-11/blob/master/communication/authorization.md)

**Comment by Mei-Sakura** [comment]
> 可以在url部分配置access_token鉴权

感谢
