### ISSUE TITLE
Docker下运行失败，求助

### ISSUE THREAD

**Issue by Speechless22** [Womsxd/MihoyoBBSTools#20]
stderr: 2023-03-27T22:25:20 INFO 使用DOCKER运行米游社签到
stderr: 2023-03-27T22:25:20 INFO Starting signing
stderr: 2023-03-27T22:25:23 INFO AutoMihoyoBBS Multi User mode
stderr: 2023-03-27T22:25:23 INFO 正在搜索配置文件！
stderr: 2023-03-27T22:25:23 INFO 已搜索到1个配置文件，正在开始执行！
stderr: 2023-03-27T22:25:23 INFO 正在执行config.yaml
stderr: 2023-03-27T22:25:23 INFO Config加载完毕
stderr: Traceback (most recent call last):
stderr:   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
stderr:     yield
stderr:   File "/usr/local/lib/python3.11/site-packages/httpcore/backends/sync.py", line 94, in connect_tcp
stderr:     sock = socket.create_connection(
stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
stderr:     raise exceptions[0]
stderr:   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
stderr:     sock.connect(sa)
stderr: ConnectionRefusedError: [Errno 111] Connection refused
stderr: 
stderr: During handling of the above exception, another exception occurred:
stderr: 
stderr: Traceback (most recent call last):
stderr:   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
stderr:     yield
stderr:   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 218, in handle_request
stderr:     resp = self._pool.handle_request(req)
stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
stderr:     raise exc
stderr:   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
stderr:     response = connection.handle_request(request)
stderr:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 86, in handle_request
stderr:     raise exc
stderr:   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 63, in handle_request
stderr:     stream = self._connect(request)
stderr:              ^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 111, in _connect
stderr:     stream = self._network_backend.connect_tcp(**kwargs)
stderr:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.11/site-packages/httpcore/backends/sync.py", line 93, in connect_tcp
stderr:     with map_exceptions(exc_map):
stderr:   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
stderr:     self.gen.throw(typ, value, traceback)
stderr:   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
stderr:     raise to_exc(exc)
stderr: httpcore.ConnectError: [Errno 111] Connection refused
stderr: 
stderr: The above exception was the direct cause of the following exception:
stderr: 
stderr: Traceback (most recent call last):
stderr:   File "/var/app/./main_multi.py", line 86, in <module>
stderr:     main_multi(autorun)
stderr:   File "/var/app/./main_multi.py", line 52, in main_multi
stderr:     run_code, run_message = main.main()
stderr:                             ^^^^^^^^^^^
stderr:   File "/var/app/main.py", line 28, in main
stderr:     login.login()
stderr:   File "/var/app/login.py", line 21, in login
stderr:     data = http.get(url=setting.bbs_cookie_url.format(config.config["account"]["login_ticket"])).json()
stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1045, in get
stderr:     return self.request(
stderr:            ^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 821, in request
stderr:     return self.send(request, auth=auth, follow_redirects=follow_redirects)
stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 908, in send
stderr:     response = self._send_handling_auth(
stderr:                ^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 936, in _send_handling_auth
stderr:     response = self._send_handling_redirects(
stderr:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 973, in _send_handling_redirects
stderr:     response = self._send_single_request(request)
stderr:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1009, in _send_single_request
stderr:     response = transport.handle_request(request)
stderr:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 217, in handle_request
stderr:     with map_httpcore_exceptions():
stderr:   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
stderr:     self.gen.throw(typ, value, traceback)
stderr:   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
stderr:     raise mapped_exc(message) from exc
stderr: httpx.ConnectError: [Errno 111] Connection refused
stderr: 2023-03-27T22:29:44 INFO Current running datetime: 2023-03-27 22:29:44
stderr: 2023-03-27T22:29:44 INFO Next run datetime: 2023-03-28 09:30:38

**Comment by Speechless22** [comment]
宿主机是OpenWrt，容器似乎没连上网，不知道咋办

**Comment by Steve5wutongyu6** [comment]
我也遇到了同样的问题，似乎是开始游戏签到后才出现的
![image](https://github.com/Womsxd/MihoyoBBSTools/assets/77491648/358b0ad9-e9e0-4a16-b4a5-5ffe50b13d2d)
![image](https://github.com/Womsxd/MihoyoBBSTools/assets/77491648/50a73192-0c97-43a6-960f-5ff99de45989)
