### ISSUE TITLE
米游社签到不了

### ISSUE THREAD

**Issue by Cedric-Zyh** [Womsxd/MihoyoBBSTools#212]
<img width="811" alt="image" src="https://github.com/user-attachments/assets/a8e0b783-0fc1-4830-863a-dc89554fee5d">
不知道是哪里的原因，米游社签到不了
<img width="531" alt="image" src="https://github.com/user-attachments/assets/06242591-7acc-47f8-b67e-d64a1f0b0c6e">

**Comment by Womsxd** [comment]
客户端类型别动，用Android，type为2

**Comment by Cedric-Zyh** [comment]
> 客户端类型别动，用Android，type为2

我四种都试了，都不行

**Comment by kafuneri** [comment]
我也遇到了这个问题，执行`pip uninstall httpx`移除httpx恢复正常签到你试试

**Comment by Cedric-Zyh** [comment]
> 我也遇到了这个问题，可能是httpx的版本问题？执行`pip uninstall httpx`移除httpx恢复正常签到，你试试

我这里并不能解决问题，不知道为什么用getDS2，salt_x6不行

**Comment by kafuneri** [comment]
> > 我也遇到了这个问题，可能是httpx的版本问题？执行`pip uninstall httpx`移除httpx恢复正常签到，你试试
> 
> 我这里并不能解决问题，不知道为什么用getDS2，salt_x6不行

直接dokcer部署算了，docker不太可能有毛病

**Comment by Womsxd** [comment]
#213

**Comment by Womsxd** [comment]
应该修好了

**Comment by Cedric-Zyh** [comment]
修好了，👍
