### ISSUE TITLE
原神登录触发验证码

### ISSUE THREAD

**Issue by kk-dark** [Womsxd/MihoyoBBSTools#3]
请教一下原神登录触发三次验证码后失败如何解决？

**Comment by limx2021** [comment]
我改成自己设备的UA就不会了

**Comment by kk-dark** [comment]
@limx2021 感谢

**Comment by fiyong12138** [comment]
。我第一天可以 后面一直触发验证码怎么办啊 ，换了ua也不行

**Comment by Yuiffy** [comment]
> 。我第一天可以 后面一直触发验证码怎么办啊 ，换了ua也不行

个人经验是触发后就自己手动过验证码签几天，签3天，它就又没验证码了，勉强能自动签几天

**Comment by tanmx** [comment]
有个云崽qq机器人，我同事用它手动签到好像挺稳的 可惜是 nodejs 的看不懂，大佬能研究下他是怎么过验证的么？
https://gitee.com/Le-niao/Yunzai-Bot

**Comment by yriiolik** [comment]
有能力可以自己修改一下 captcha.py ，对接一下网上的一些打码api。 可以实现自动签到。
