### ISSUE TITLE
社区打卡的DS算法是怎样的？

### ISSUE THREAD

**Issue by wang0251** [Womsxd/MihoyoBBSTools#37]
原神签到自动打码的弄好了，想自己弄个自动打卡的模板，试了几种DS算法都不对

**Comment by Womsxd** [comment]
https://github.com/Womsxd/MihoyoBBSTools/blob/1a203bd463a7860fb896ffb807c4879d125150fd/tools.py#L40-L46

**Comment by Womsxd** [comment]
header["DS"] = tools.get_ds2("", json.dumps({"gids": forum["id"]}))

**Comment by wang0251** [comment]
搞定了，感谢大佬
