### ISSUE TITLE
No module named 'gamecheckin'

### ISSUE THREAD

**Issue by fiyong12138** [Womsxd/MihoyoBBSTools#39]
运行报错，python也无法安装这个模块

Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main.swap.py", line 7, in <module>

    import honkai2
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/honkai2.py", line 2, in <module>
    from gamecheckin import GameCheckin
ModuleNotFoundError: No module named 'gamecheckin'

**Comment by Womsxd** [comment]
已经修复，请更新青龙面板里需要拉取的文件

**Comment by Womsxd** [comment]
名称：米游社签到
类型：公开仓库
链接：https://github.com/Womsxd/MihoyoBBSTools.git
定时类型：crontab
定时规则：2 2 28 * *
白名单：ql_main.py
依赖文件：error|mihoyo|genshin|honkai3rd|log|push|req|set|tools|con|acc|honkai2|tearsofthemis|captcha|main|gamecheckin|honkaisr|hoyo_checkin|hoyo_gs|hoyo_http|hoyo_sr
