### ISSUE TITLE
青龙面板 怎么多用户啊

### ISSUE THREAD

**Issue by fiyong12138** [Womsxd/MihoyoBBSTools#4]

**Comment by kk-dark** [comment]
哈哈，同问，作者大佬有空可以模仿jd脚本挂ck

**Comment by CN-YoungYang** [comment]
运行main_multi.py 就可以 多个用户,  通知就需要你自己想办法改改代码

**Comment by nyano** [comment]
计划任务中 改为 task Womsxd_MihoyoBBSTools/main_multi.py
在main_multi.py中
将： input("请输入回车继续，需要重新搜索配置文件请Ctrl+C退出脚本")
改为：pass
即可多用户。但是无推送。在文件最上方添加：import notify
将：push.push(status, push_message)
改为：notify.send(status, push_message)
应该是对的，但是我能执行但是还是无通知，未能调用notify.py


另外：
2023-02-21T09:49:37 WARNING 社区签到触发验证码
2023-02-21T09:49:38 WARNING 社区签到触发验证码
2023-02-21T09:49:39 WARNING 社区签到触发验证码
2023-02-21T09:49:39 WARNING 社区签到触发验证码
我还记得当初是因为有出现有剩余经验未获得，所以设置成了3遍重复运行。
但是是否可以在某个环节出发验证码后，跳过这个环节，如签到，以便减少触发验证码可能性。另外，增加随机延迟也有一定作用？
社区签到和游戏签到的验证码是联动的，触发一个，则同时有验证码，反之亦然。

最后，云原神的token怎么获得？
为什么突然换仓库名了。。。

**Comment by nyano** [comment]
将订阅白名单改为：ql_main.py|main_multi.py|notify.py|main.py
然后重新对文件进行修改，推送成功了
