### ISSUE TITLE
云原神的TOKEN怎么抓包啊？

### ISSUE THREAD

**Issue by i-cecreamer** [Womsxd/MihoyoBBSTools#40]
我跟着QQ机器人教程抓的TOKEN，机器人能识别，一跑代码就是错误

**Comment by i-cecreamer** [comment]
![QQ截图20230507013344](https://user-images.githubusercontent.com/128817713/236638773-08fb795f-80f2-4342-a2ab-7db008bfa916.png)

**Comment by i-cecreamer** [comment]
![image](https://user-images.githubusercontent.com/128817713/236639009-4f44fe5f-d201-4bd1-b662-6f506b8abafc.png)

**Comment by bangbang23333** [comment]
我直接在手机上用httpcanary抓的，可以试试
