### ISSUE TITLE
签到时返回 429 Too Many Requests 错误，程序报错并退出了

### ISSUE THREAD

**Issue by Yatogamikaka** [Womsxd/MihoyoBBSTools#42]
![1HMU67H}8D@3S531UXC`ME8](https://user-images.githubusercontent.com/44599100/236689784-6ed4ad80-a685-45be-bb8e-04f6b8f83416.png)

如图上所示

**Comment by Womsxd** [comment]
ip请求次数过多，云函数可以考虑切换地区/修改执行时间
