### ISSUE TITLE
希望可以加入验证码打码平台功能

### ISSUE THREAD

**Issue by 2375399351** [Womsxd/MihoyoBBSTools#43]
这样应该就可以过验证码了，自费就行

**Comment by keaiye** [comment]
[captcha.py](https://github.com/Womsxd/MihoyoBBSTools/blob/master/captcha.py)

**Comment by Womsxd** [comment]
有预留的对接，但是需要用户自己去对接使用才行
本人也不会直接推荐你去用xxx平台
