### ISSUE TITLE
风控:添加新增请求头,

### ISSUE THREAD

**Issue by CN-YoungYang** [Womsxd/MihoyoBBSTools#49]
群里面有个人 添加了新的请求头稳定了 近半年,。。 

具体请求头 他没说出来。

![image](https://github.com/Womsxd/MihoyoBBSTools/assets/25340441/82248049-f318-4d9e-8595-84edd7959545)

**Comment by sykeswzq** [comment]
去详细问问呗

**Comment by CN-YoungYang** [comment]
> 去详细问问呗

那人潜水了, 

![image](https://github.com/Womsxd/MihoyoBBSTools/assets/25340441/5d229fca-3812-4a12-a45e-bd3452279402)

**Comment by sykeswzq** [comment]
好吧。。。。问一下你知道多账号推送怎么修改吗？

我现在推送出来是个奇怪的东西

**Comment by Night-stars-1** [comment]
没用的添加请求头并不会解决风控，python等的网络请求都是带特征的这并不是简单的更改请求头可以解决的，实际上不同语音触发验证码的概率是不同的，php写的获取体力的接口在过去的一年里都没有触发验证码，而python实现很容易触发
