### ISSUE TITLE
好吧。。。。问一下你知道多账号推送怎么修改吗？

### ISSUE THREAD

**Issue by sykeswzq** [Womsxd/MihoyoBBSTools#50]
好吧。。。。问一下你知道多账号推送怎么修改吗？

我现在推送出来是个奇怪的东西

脚本执行完毕，共执行2个配置文件，成功2个，没执行0个，失败0个

没执行的配置文件: []

执行失败的配置文件: []

触发原神验证码的配置文件: []
_Originally posted by @sykeswzq in https://github.com/Womsxd/MihoyoBBSTools/issues/49#issuecomment-1545017139_

**Comment by CN-YoungYang** [comment]
这个就是正常的推送。  你要是想 推送具体信息，就要 在main函数里面把 信息值返回出来。然后 推出来。  具体的代码 你自己研究下， 思路就是上面的。

**Comment by sykeswzq** [comment]
好吧，感谢

**Comment by CN-YoungYang** [comment]
个人推荐，要是 推送的没次数限制。。

你就两个账号， 不如 分开 运行单账号。 分两次托送。  

尽量不去改作者代码

分开运行，你可以 利用 宝塔的 计划任务 覆盖 文件，然后青龙里面在 执行

**Comment by sykeswzq** [comment]
我去尝试下

**Comment by sykeswzq** [comment]
有点难搞 感觉要改的有点多。。。放弃

**Comment by sykeswzq** [comment]
我把自己账号弄了个单的推送 哈哈 先混着吧

**Comment by CN-YoungYang** [comment]
还好吧。 
第一步, 将 2个账号 名字修改。
第二步 宝塔计划任务  创建两个计划任务
                - 替换账号1
                - 替换帐号2
第三部 执行青龙脚本
                - 账号1
                - 账号2

其中  替换和执行 的时间你整好就可以

执行代码 你就下面这个改。 路径 文件名 你自己控制。   不是直接复制下面的啊
cp ./config/Mihoyo/Data/captcha.py ./scripts/Womsxd_MihoyoBBSTools/captcha.py

**Comment by sykeswzq** [comment]
也行

**Comment by Womsxd** [comment]
多用户推送就是这样子的，方便查看，同时对于有次数限制或文本长度限制的推送接口较为友好一点

**Comment by Womsxd** [comment]
#47
