### ISSUE TITLE
多任务米游社讨论区/崩坏星穹铁道签到触发验证码不推送

### ISSUE THREAD

**Issue by hanbao233xD** [Womsxd/MihoyoBBSTools#57]
运行的是多任务脚本（main_multi.py），因为适配青龙的版本推送不发消息所以就没用
机器人推送结果：
![微信截图_20230526125442](https://github.com/Womsxd/MihoyoBBSTools/assets/39661586/1d53632f-2474-4ee1-8a58-d17e2839fd61)

日志带uid，就不放源文件了
![微信截图_20230526125128](https://github.com/Womsxd/MihoyoBBSTools/assets/39661586/b122c940-5bdf-4bf3-bb9b-bd9bb6078100)
![微信截图_20230526125402](https://github.com/Womsxd/MihoyoBBSTools/assets/39661586/20d698ec-df49-4486-97f4-7b5a75705850)

**Comment by sykeswzq** [comment]
解决了吗

**Comment by TonyWang2233** [comment]
the same problem..
