### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\xa0' in position 103: ordinal not in range(128)

### ISSUE THREAD

**Issue by jqtmviyu** [Womsxd/MihoyoBBSTools#6]
不太确定是不是因为使用默认模板的原因
我最后换成automihoyobbs-mihoyo-bbs的模板了
(ps:也可能是因为我复制出错:doge)

**Comment by Mo-Qiong** [comment]
粘贴 http://user.mihoyo.com/ 的cookie时在最后加了个 ;[空格] 会导致报错。
