### ISSUE TITLE
captcha.py里该怎么对接打码平台

### ISSUE THREAD

**Issue by 3054528216** [Womsxd/MihoyoBBSTools#60]
有大佬给个教程吗

**Comment by yunigongshang** [comment]
![image](https://github.com/Womsxd/MihoyoBBSTools/assets/110106117/8c0e87b1-696c-4b5e-a684-d31aef9eb7d3)

**Comment by yunigongshang** [comment]
> 

使用的是人人图像打码http://www.rrocr.com/，需要收费10r10000积分，打码一次25积分

**Comment by yunigongshang** [comment]
如果有免费的请分享一下

**Comment by 3054528216** [comment]
> ![image](https://user-images.githubusercontent.com/110106117/250281881-8c0e87b1-696c-4b5e-a684-d31aef9eb7d3.png)

老哥能复制出来吗，我手打貌似报错

**Comment by yunigongshang** [comment]
> > ![image](https://user-images.githubusercontent.com/110106117/250281881-8c0e87b1-696c-4b5e-a684-d31aef9eb7d3.png)
> 
> 老哥能复制出来吗，我手打貌似报错
def game_captcha(gt: str, challenge: str):
    rep = http.post(
        url= "http://api.rrocr.com/api/recognize.html",
        data={
            "appkey": "",
            "gt": gt,
            "challenge" : challenge,
            "referer" : "https://api-takumi.mihoyo.com/event/bbs_sign_reward/sign"
        }
    ).json()
    return rep["data"]["validate"]

**Comment by yunigongshang** [comment]
> > ![image](https://user-images.githubusercontent.com/110106117/250281881-8c0e87b1-696c-4b5e-a684-d31aef9eb7d3.png)
> 
> 老哥能复制出来吗，我手打貌似报错

我今天还没试过，你把代码发出来看看吧

**Comment by 3054528216** [comment]
> > > ![image](https://user-images.githubusercontent.com/110106117/250281881-8c0e87b1-696c-4b5e-a684-d31aef9eb7d3.png)
> > 
> > 
> > 老哥能复制出来吗，我手打貌似报错
> 
> 我今天还没试过，你把报错代码发出来看看吧

我百度了一下应该是空格回车之类的问题，现在不报错了，但现在签到不上了

**Comment by yunigongshang** [comment]
> 

你这样说我也不知道什么问题，我也不知道你日志是什么情况，如果你用的人人图像打码可以去看看是否打码成功
`def game_captcha(gt: str, challenge: str):
    rep = http.post(
        url= "http://api.rrocr.com/api/recognize.html",
        data={
            "appkey": "",
            "gt": gt,
            "challenge" : challenge,
            "referer" : "https://api-takumi.mihoyo.com/event/bbs_sign_reward/sign"
        }
    ).json()
    return rep["data"]["validate"]`

**Comment by 3054528216** [comment]
> > 
> 
> 你这样说我也不知道什么问题，我也不知道你日志是什么情况，如果你用的人人图像打码可以去看看是否打码成功 `def game_captcha(gt: str, challenge: str): rep = http.post( url= "http://api.rrocr.com/api/recognize.html", data={ "appkey": "", "gt": gt, "challenge" : challenge, "referer" : "https://api-takumi.mihoyo.com/event/bbs_sign_reward/sign" } ).json() return rep["data"]["validate"]`

不是打码方面的问题，是米游社签到更新了新东西现在脚本签不上

**Comment by yunigongshang** [comment]
> > > 
> > 
> > 
> > 你这样说我也不知道什么问题，我也不知道你日志是什么情况，如果你用的人人图像打码可以去看看是否打码成功`def game_captcha(gt: str, challenge: str): rep = http.post( url= "http://api.rrocr.com/api/recognize.html", data={ "appkey": "", "gt": gt, "challenge" : challenge, "referer" : "https://api-takumi.mihoyo.com/event/bbs_sign_reward/sign" } ).json() return rep["data"]["validate"]`
> 
> 不是打码方面的问题，是米游社签到更新了新东西现在脚本签不上

我今天用的还可以签到

**Comment by 2314933036** [comment]
> > > 
> > 
> > 
> > 你这样说我也不知道什么问题，我也不知道你日志是什么情况，如果你用的人人图像打码可以去看看是否打码成功 `def game_captcha(gt: str, challenge: str): rep = http.post( url= "http://api.rrocr.com/api/recognize.html", data={ "appkey": "", "gt": gt, "challenge" : challenge, "referer" : "https://api-takumi.mihoyo.com/event/bbs_sign_reward/sign" } ).json() return rep["data"]["validate"]`
> 
> 不是打码方面的问题，是米游社签到更新了新东西现在脚本签不上

我刚签完

**Comment by 3054528216** [comment]
> > > > 
> > > 
> > > 
> > > 你这样说我也不知道什么问题，我也不知道你日志是什么情况，如果你用的人人图像打码可以去看看是否打码成功`def game_captcha(gt: str, challenge: str): rep = http.post( url= "http://api.rrocr.com/api/recognize.html", data={ "appkey": "", "gt": gt, "challenge" : challenge, "referer" : "https://api-takumi.mihoyo.com/event/bbs_sign_reward/sign" } ).json() return rep["data"]["validate"]`
> > 
> > 
> > 不是打码方面的问题，是米游社签到更新了新东西现在脚本签不上
> 
> 我今天用的还可以签到

可能是我ck出问题了

**Comment by yunigongshang** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 你这样说我也不知道什么问题，我也不知道你日志是什么情况，如果你用的人人图像打码可以去看看是否打码成功`def game_captcha(gt: str, challenge: str): rep = http.post( url= "http://api.rrocr.com/api/recognize.html", data={ "appkey": "", "gt": gt, "challenge" : challenge, "referer" : "https://api-takumi.mihoyo.com/event/bbs_sign_reward/sign" } ).json() return rep["data"]["validate"]`
> > > 
> > > 
> > > 不是打码方面的问题，是米游社签到更新了新东西现在脚本签不上
> > 
> > 
> > 我今天用的还可以签到
> 
> 可能是我ck出问题了

获取cookie，开无痕/隐身模式登入米游社和米哈游通行证，F12获取米哈游通行证试试，米游社和米哈游通行证都要登入

**Comment by 3054528216** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 你这样说我也不知道什么问题，我也不知道你日志是什么情况，如果你用的人人图像打码可以去看看是否打码成功`def game_captcha(gt: str, challenge: str): rep = http.post( url= "http://api.rrocr.com/api/recognize.html", data={ "appkey": "", "gt": gt, "challenge" : challenge, "referer" : "https://api-takumi.mihoyo.com/event/bbs_sign_reward/sign" } ).json() return rep["data"]["validate"]`
> > > > 
> > > > 
> > > > 不是打码方面的问题，是米游社签到更新了新东西现在脚本签不上
> > > 
> > > 
> > > 我今天用的还可以签到
> > 
> > 
> > 可能是我ck出问题了
> 
> 获取cookie，开无痕/隐身模式登入米游社和米哈游通行证，F12获取米哈游通行证试试，米游社和米哈游通行证都要登入

前几天还能用的，估计是过期了

**Comment by caisxg** [comment]
@3054528216  这个模板还可以用吗? 我最近想触发风控,发现死活不出验证码?

**Comment by caisxg** [comment]
顺便问一下, 知道这个验证码是那种类型的验证码吗? 比如极验 3 还是极验 4?

**Comment by yunigongshang** [comment]
> 顺便问一下, 知道这个验证码是那种类型的验证码吗?比如极验 3 还是极验 4?

三代特殊图

**Comment by nomoneynolife** [comment]
666可行，起飞。。

**Comment by 3054528216** [comment]
> > 
> 
> 你这样说我也不知道什么问题，我也不知道你日志是什么情况，如果你用的人人图像打码可以去看看是否打码成功 `def game_captcha(gt: str, challenge: str): rep = http.post( url= "http://api.rrocr.com/api/recognize.html", data={ "appkey": "", "gt": gt, "challenge" : challenge, "referer" : "https://api-takumi.mihoyo.com/event/bbs_sign_reward/sign" } ).json() return rep["data"]["validate"]`

](url)
![071EC9B029BFE8877D6695D6F542CADC](https://github.com/Womsxd/MihoyoBBSTools/assets/106349461/c69b2c34-94d6-49db-8566-435d9c1f2bda)
![6A1ECB07B674917EDE601D15EC704148](https://github.com/Womsxd/MihoyoBBSTools/assets/106349461/66aa8169-1078-4a15-826b-bc7ebff34295)

**Comment by 3054528216** [comment]
> > 
> 
> 你这样说我也不知道什么问题，我也不知道你日志是什么情况，如果你用的人人图像打码可以去看看是否打码成功 `def game_captcha(gt: str, challenge: str): rep = http.post( url= "http://api.rrocr.com/api/recognize.html", data={ "appkey": "", "gt": gt, "challenge" : challenge, "referer" : "https://api-takumi.mihoyo.com/event/bbs_sign_reward/sign" } ).json() return rep["data"]["validate"]`

![00B8F2CEB5685AC84400DD734493CB69](https://github.com/Womsxd/MihoyoBBSTools/assets/106349461/31e72d42-d775-4d3a-985d-4804b1600749)

**Comment by sykeswzq** [comment]
> ![image](https://user-images.githubusercontent.com/110106117/250281881-8c0e87b1-696c-4b5e-a684-d31aef9eb7d3.png)

![1](https://github.com/Womsxd/MihoyoBBSTools/assets/97281429/b397adfa-c5e4-4638-a149-d4bce0441d5b)
大佬，这个怎么回事啊
