### ISSUE TITLE
Cookie没有问题，但是重试多次依然无法正常签到，米游社自动签到正常，手动签到正常

### ISSUE THREAD

**Issue by bangbang23333** [Womsxd/MihoyoBBSTools#62]
2023-06-28T00:19:56 INFO 正在获取签到奖励列表...
2023-06-28T00:19:56 INFO 正在为旅行者荧进行签到...
2023-06-28T00:20:02 WARNING 获取账号签到信息失败！
{"data":null,"message":"尚未登录","retcode":-100}
2023-06-28T00:20:02 INFO Config保存完毕
2023-06-28T00:20:02 ERROR 账号Cookie有问题！

**Comment by 3054528216** [comment]
我也是，貌似游戏公告里说这个签到更新了啥东西

**Comment by yunigongshang** [comment]
> 2023-06-28T00:19:56 INFO 正在获取签到奖励列表... 2023-06-28T00:19:56 INFO 正在为旅行者荧进行签到... 2023-06-28T00:20:02 WARNING 获取账号签到信息失败！ {"data":null,"message":"尚未登录","retcode":-100} 2023-06-28T00:20:02 INFO Config保存完毕 2023-06-28T00:20:02 ERROR 账号Cookie有问题！

获取cookie，最好打开隐私模式（虽然我也不知道是不是一定要）然后米游社和米哈游通行证都要登入，F12获取米哈游通行证的cookie就能用了，我是这样弄的

**Comment by 2514211359** [comment]
@yunigongshang 大佬，你说的cookie获取用的是作者那种方式获取得嘛

**Comment by yunigongshang** [comment]
> @yunigongshang 大佬，你说的cookie获取用的是作者那种方式获取得嘛

我不是,我用的是另一种方法

**Comment by 2514211359** [comment]
@yunigongshang 方便细
说一下嘛

**Comment by yunigongshang** [comment]
> @yunigongshang 方便细 说一下嘛

我上面不是说了教程吗，你可以看一下

**Comment by bangbang23333** [comment]
> > @yunigongshang 方便细 说一下嘛
> 
> 我上面不是说了教程吗，你可以看一下

wwwww一样的方法，照样没用，各种方式都试过了才来反馈的QAQ

**Comment by yunigongshang** [comment]
> > > @yunigongshang 方便细 说一下嘛
> > 
> > 
> > 我上面不是说了教程吗，你可以看一下
> 
> wwwww一样的方法，照样没用，各种方式都试过了才来反馈的QAQ

我是按照这里面的方法获取的https://docs.qq.com/doc/DZFF0aWRzcGhRcWd4，获取了cookie后粘贴到他的程序里面会生成一个配置文件，里面有已经分离好的stoken和cookie，最后再填到这个项目的里面，只能帮你到这里了

**Comment by bangbang23333** [comment]
> 重拉库

后面发现是我自己的问题，cookie要把那个冒号覆盖掉，不然只有米游社可以正常签到，游戏是无法签到的
