### ISSUE TITLE
崩坏3签到失败

### ISSUE THREAD

**Issue by loliconss** [Womsxd/MihoyoBBSTools#63]
崩坏3签到失败。可以获取到崩坏3角色列表但是在请求https://api-takumi.mihoyo.com/event/luna/info接口的时候失败返回{"data":null,"message":"","retcode":-100}
无法成功签到

**Comment by loliconss** [comment]
正常的帖子什么都正常。而且能获取到角色列表。请问是请求头参数之类的接口改了嘛

**Comment by Womsxd** [comment]
已修复
