### ISSUE TITLE
崩坏三签到报错

### ISSUE THREAD

**Issue by gggssepgf** [Womsxd/MihoyoBBSTools#64]
应该是因为今天崩坏三更新了签到的关系，用工具签到会报错

mihoyobbstools-mihoyo-bbs-1  | 2023-07-01T11:54:18 INFO 正在获取签到奖励列表...
mihoyobbstools-mihoyo-bbs-1  | 2023-07-01T11:54:18 INFO HTTP Request: GET https://api-takumi.mihoyo.com/event/luna/home?lang=zh-cn&act_id=e202207181446311 "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-07-01T11:54:18 INFO 正在为舰长喝冰水的冰水进行签到...
mihoyobbstools-mihoyo-bbs-1  | 2023-07-01T11:54:26 INFO HTTP Request: GET https://api-takumi.mihoyo.com/event/luna/info?lang=zh-cn&act_id=e202207181446311&region=android01&uid=10338653 "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-07-01T11:54:26 WARNING 获取账号签到信息失败！
mihoyobbstools-mihoyo-bbs-1  | 2023-07-01T11:54:26 INFO Config保存完毕
mihoyobbstools-mihoyo-bbs-1  | 2023-07-01T11:54:26 INFO config1.yaml执行完毕
mihoyobbstools-mihoyo-bbs-1  | 2023-07-01T11:54:32 INFO 脚本执行完毕，共执行2个配置文件，成功1个，没执行0个，失败1个
mihoyobbstools-mihoyo-bbs-1  | 没执行的配置文件: []
mihoyobbstools-mihoyo-bbs-1  | 执行失败的配置文件: ['config1.yaml']
mihoyobbstools-mihoyo-bbs-1  | 触发原神验证码的配置文件: []
mihoyobbstools-mihoyo-bbs-1  | 2023-07-01T11:54:32 INFO 正在执行推送......
mihoyobbstools-mihoyo-bbs-1  | 2023-07-01T11:54:32 INFO HTTP Request: GET http://api.iw233.cn/api.php?sort=random&type=json "HTTP/1.1 301 Moved Permanently"
mihoyobbstools-mihoyo-bbs-1  | 2023-07-01T11:54:32 WARNING 获取随机背景图失败，请检查图片api
mihoyobbstools-mihoyo-bbs-1  | 2023-07-01T11:54:33 INFO 邮件发送成功啦
mihoyobbstools-mihoyo-bbs-1  | {"data":null,"message":"签到功能维护中，请耐心等待！\n更新后的前三次签到可获得共计120水晶~","retcode":-500007}
用手机米游社可以正常签到，所以不是正在维护，应该是改了接口

**Comment by Womsxd** [comment]
已修复
