### ISSUE TITLE
【建议】如果自己接入了打码平台，订阅管理中依赖文件要把captcha删掉

### ISSUE THREAD

**Issue by GhostarDragon** [Womsxd/MihoyoBBSTools#69]
如果自己接入了打码平台，订阅管理中依赖文件要把captcha删掉，不然自动更新订阅或者手动运行更新时，会把你写的接入代码覆盖掉。（别问我这么知道的

**Comment by qxFly** [comment]
兄弟，你用的打码平台是那个，可以给个链接吗

**Comment by caisxg** [comment]
问一下, 接入打码平台说明文档吗? 能否有一个模板...不知道怎么使用

**Comment by caisxg** [comment]
比如这里面应该返回什么? 顺便问一下,这个验证码使用的极验 3 还是极验 4 呀?没看懂
```

from request import http


def game_captcha(gt: str, challenge: str):
    return None  # 失败返回None 成功返回validate


def bbs_captcha(gt: str, challenge: str):
    return None
```

**Comment by hggg666** [comment]
> 如果自己接入了打码平台，订阅管理中依赖文件要把captcha删掉，不然自动更新订阅或者手动运行更新时，会把你写的接入代码覆盖掉。（别问我这么知道的

请问楼主用的什么面板拉源码的?我用的a面板把captcha都加到黑名单里了还是会覆盖
