### ISSUE TITLE
个人总结避免验证码的技巧以及简单抓取UA的方法

### ISSUE THREAD

**Issue by CirnoSalt** [Womsxd/MihoyoBBSTools#7]
1：由于脚本会自动追加UA中最后一段的米游社版本字段，并且这个参数似乎还会随app版本自动更新，所以需要尽量保持自己设备上的米游社app处于最新版本，否则会因UA不同而触发风控。
  
2：如果你使用Android设备并且正在使用Play商店，那么系统的WebView可能会被play商店自动更新，此时UA也会有变化导致触发风控，需要重新抓取UA并更新配置文件，ios设备OTA也可能会导致UA变化。
  
亲测做到脚本UA尽量保持和自己的设备app内同步可以大大降低触发验证码封控的概率！
  
附带最简单的抓取app内UA方式，无需抓包：
用米游社app打开这个帖子：
[米游社UA抓取](https://m.miyoushe.com/ys?channel=xiaomi/#/article/12394963) 
![Screenshot_2023-02-24-10-13-54-002_com mihoyo hyperion-edit](https://user-images.githubusercontent.com/23478997/221075208-5a1ff66a-4fd6-4cab-9fd6-7481dfcecd23.jpg)
（为了下次抓取更方便，可以收藏这个帖子，下次直接从收藏中打开）
如果无法跳转，可以手动搜索用户或帖子标题。
点击“米游社UA”的蓝链，
复制“服务端获取的UserAgent”下内容填写到脚本配置文件的UA设置，手动删除最后“miHoYoBBS/版本”字段即可。

**Comment by Mo-Qiong** [comment]
不行，隔两天就得更新一次，放弃了，不如手动签到。这玩意帮我弄弄麻烦但也没什么用的米游币得了。

**Comment by CirnoSalt** [comment]
> 不行，隔两天就得更新一次，放弃了，不如手动签到。这玩意帮我弄弄麻烦但也没什么用的米游币得了。

确实，失效了……
