### ISSUE TITLE
INFO HTTP Request: GET https://api-takumi.miyoushe.com/binding/api/getUserGameRolesByCookie?game_biz=hk4e_cn "HTTP/1.1 200 OK"

### ISSUE THREAD

**Issue by sykeswzq** [Womsxd/MihoyoBBSTools#80]
出现这个情况是什么意思？请问怎么解决？
![1](https://github.com/Womsxd/MihoyoBBSTools/assets/97281429/4a08a2d0-ddcc-40a5-9449-4b90dc5ac31f)

**Comment by sykeswzq** [comment]
以前没有的，好像是你这种更新完才出来的

**Comment by sykeswzq** [comment]
以前没有的，好想是更新完才出来的

**Comment by Womsxd** [comment]
依赖httpx更新后出现的
