### ISSUE TITLE
帖子签到不了了

### ISSUE THREAD

**Issue by sykeswzq** [Womsxd/MihoyoBBSTools#88]
![image](https://github.com/Womsxd/MihoyoBBSTools/assets/97281429/52638501-579c-4db9-b599-40726dfc46e3)
更新了新版，帖子点赞不了了，请问什么问题

**Comment by atigger** [comment]
+1

**Comment by Womsxd** [comment]
感觉是改出bug了，尝试更新下看看

**Comment by sykeswzq** [comment]
更新下没用，老样子

**Comment by Womsxd** [comment]
已确认可正常使用/修复?

**Comment by sykeswzq** [comment]
> 已确认可正常使用/修复?

![1](https://github.com/Womsxd/MihoyoBBSTools/assets/97281429/8cf949c0-5fca-45ff-b461-65f4900828ae)
还是不能签到，config已改true

**Comment by Womsxd** [comment]
???你试试拉最新的代码，在群里的话pm我
