### ISSUE TITLE
获取帖子列表失败

### ISSUE THREAD

**Issue by vesugier** [Womsxd/MihoyoBBSTools#89]
![图片](https://github.com/Womsxd/MihoyoBBSTools/assets/66554786/42d0c2e2-538b-4525-8375-f8d7368a386f)

**Comment by Womsxd** [comment]
老米服务器炸了重新跑脚本吧



发件人: ***@***.***>
发送时间: 2023年10月15日 16:26
收件人: ***@***.***>
抄送: ***@***.***>
主题: [Womsxd/MihoyoBBSTools] 获取帖子列表失败 (Issue #89)


[图片]<https://user-images.githubusercontent.com/66554786/275314313-42d0c2e2-538b-4525-8375-f8d7368a386f.png>

―
