### ISSUE TITLE
从22号开始，签到日志显示成功，但是实际签到失败

### ISSUE THREAD

**Issue by f59375543** [Womsxd/MihoyoBBSTools#9]
我昨天手动补签了一下，没有碰到验证码，不是因为触发验证码而签到失败

今天手动激活脚本两次，都是显示签到成功，但是并没有成功

![20230226223938](https://user-images.githubusercontent.com/43315911/221417370-e51afb6e-0b84-48ca-9420-913c2d7fdf56.png)
![20230226224009](https://user-images.githubusercontent.com/43315911/221417383-225f779c-c62e-4b70-bf36-19d692717f6b.jpg)

**Comment by FairyJJ** [comment]
我也一样

**Comment by Womsxd** [comment]
该不会也上验证码了吧

**Comment by f59375543** [comment]
> 该不会也上验证码了吧

没有触发验证码，所以很奇怪，手动签到的时候也没有提示需要进行验证，点一下就自动签上了

**Comment by Womsxd** [comment]
感觉和之前原神差不多的情况，小范围先上验证码，然后拓展过去

________________________________
