### ISSUE TITLE
每日打卡的地方变了，原来的脚本无法继续打卡

### ISSUE THREAD

**Issue by NekoMua** [Womsxd/MihoyoBBSTools#91]
米游社更新之后，原来打卡的地方变了，原神的在下面的酒馆板块，大别野的在ACG板块，星铁在候车室板块

**Comment by taskmgr818** [comment]
![image](https://github.com/Womsxd/MihoyoBBSTools/assets/124493597/5648ffaf-9e71-4471-9f06-6aebc373aa74)

2023-11-6仍然可以，应该只是改了UI，没有改API

**Comment by NekoMua** [comment]
> ![image](https://github.com/Womsxd/MihoyoBBSTools/assets/124493597/5648ffaf-9e71-4471-9f06-6aebc373aa74)
> 
> 2023-11-6仍然可以，应该只是改了UI，没有改API

今天看了，好像是的，麻烦了哈
