### ISSUE TITLE
每日打卡API变了，设置了打码平台的请更新

### ISSUE THREAD

**Issue by LikeFlyingPanda** [Womsxd/MihoyoBBSTools#95]
<img width="631" alt="捕获" src="https://github.com/Womsxd/MihoyoBBSTools/assets/57307046/fc3e068b-85c6-4157-b256-879dcd6f1409">

我用的是人人图像打码平台

游戏签到api变成 https://api-takumi.mihoyo.com/event/luna/sign
社区签到api变成 https://bbs-api.miyoushe.com/apihub/app/api/signIn

from request import http

def game_captcha(gt: str, challenge: str): 
    rep = http.post( 
        url= "http://api.rrocr.com/api/recognize.html", 
        data={ 
            "appkey": "你自己的appkey", 
            "gt": gt, 
            "challenge" : challenge, 
            "referer" : "https://api-takumi.mihoyo.com/event/luna/sign" 
            } 
    ).json() 
    return rep["data"]["validate"]

def bbs_captcha(gt: str, challenge: str):
    rep = http.post( 
        url= "http://api.rrocr.com/api/recognize.html", 
        data={ 
            "appkey": "你自己的appkey", 
            "gt": gt, 
            "challenge" : challenge, 
            "referer" : "https://bbs-api.miyoushe.com/apihub/app/api/signIn" 
            } 
    ).json() 
    return rep["data"]["validate"]

**Comment by cslinwang** [comment]
好用~，感谢

**Comment by mikuily** [comment]
我说怎么最近打码平台识别失败这么多，改好明天试试，感谢(´･ᴗ･`)

**Comment by sykeswzq** [comment]
> <img alt="捕获" width="631" src="https://user-images.githubusercontent.com/57307046/284250667-fc3e068b-85c6-4157-b256-879dcd6f1409.PNG">
> 我用的是人人图像打码平台
> 
> 游戏签到api变成 https://api-takumi.mihoyo.com/event/luna/sign 社区签到api变成 https://bbs-api.miyoushe.com/apihub/app/api/signIn
> 
> from request import http
> 
> def game_captcha(gt: str, challenge: str): rep = http.post( url= "http://api.rrocr.com/api/recognize.html", data={ "appkey": "你自己的appkey", "gt": gt, "challenge" : challenge, "referer" : "https://api-takumi.mihoyo.com/event/luna/sign" } ).json() return rep["data"]["validate"]
> 
> def bbs_captcha(gt: str, challenge: str): rep = http.post( url= "http://api.rrocr.com/api/recognize.html", data={ "appkey": "你自己的appkey", "gt": gt, "challenge" : challenge, "referer" : "https://bbs-api.miyoushe.com/apihub/app/api/signIn" } ).json() return rep["data"]["validate"]

来个截图吧，复制的不知道缩进位置。

**Comment by LikeFlyingPanda** [comment]
现在电脑不在身边，用手机截的图，先凑合看看
![Screenshot_2023-11-22-13-25-21-594_com android browser](https://github.com/Womsxd/MihoyoBBSTools/assets/57307046/88b38a29-7dca-4e1d-85ab-12538311f964)

**Comment by LikeFlyingPanda** [comment]
现在电脑不在身边，用手机截的图，先凑合看看
![IMG_20231122_132723](https://github.com/Womsxd/MihoyoBBSTools/assets/57307046/aa7a4a17-bb09-4d64-a6ef-c2c30fdfad9e)

**Comment by sykeswzq** [comment]
感谢

**Comment by sanqianyanyi** [comment]
感谢

**Comment by w211691** [comment]
![screenshot20231124](https://github.com/Womsxd/MihoyoBBSTools/assets/47178067/c6505491-d104-4c09-9622-f2b26a0118a3)
还是报错，麻烦看一下吧

**Comment by xuehantian** [comment]
> def bbs_captcha(gt: str, challenge: str):
> rep = http.post(
> url= "http://api.rrocr.com/api/recognize.html",
> data={
> "appkey": "你自己的appkey",
> "gt": gt,
> "challenge" : challenge,
> "referer" : "https://bbs-api.miyoushe.com/apihub/app/api/signIn"
> }
> ).json()
> return rep["data"]["validate"]

兄弟，这个错误解决了吗？
